package:
    name: libhlc
    version: "0.1"

source:
    path: ..

build:
    number: 6

about:
    home: https://github.com/numba/libHLC
    license: BSD
    summary: A shared lib that wraps HLC-LLVM from HSAFoundation for code generation to HSA devices

