package:
    name: libhlc
    version: "0.2"

source:
    path: ..

build:
    number: 0
    script_env:
        - LLVMCONFIG
about:
    home: https://github.com/numba/libHLC
    license: BSD
    summary: A shared lib that wraps HLC-LLVM from HSAFoundation for code generation to HSA devices

